# General Settings
DEVELOPER_MODE: false

# Dataset Configuration
DATASETS:
  - data_path: "../../data/MSVD/YouTubeClips"
    dataset: "MSVD"
    version: "all"
    modalities: [ "video" ]

  - data_path: "../../data/MSRVTT/all"
    dataset: "MSRVTT"
    version: "train"
    modalities: [ "video", "audio" ]

  - data_path: "../../data/MSRVTT/test"
    dataset: "MSRVTT"
    version: "test"
    modalities: [ "video" ]

  - data_path: "../../data/COCO/val2017"
    dataset: "COCO"
    version: "val2017"
    modalities: [ "image" ]

  - data_path: "../../data/COCO/test2017"
    dataset: "COCO"
    version: "test2017"
    modalities: [ "image" ]

# Frontend Settings
RESULT_COLUMNS: 4
CANDIDATES_PER_PAGE: 32
REQUESTS_TIMEOUT: 60000  # 60 seconds

# Backend Settings
BACKEND_URL: "http://localhost:8500"
## Milvus
MILVUS_URL: "http://localhost:19530"
MILVUS_DB_NAME: "MultimodalMediaSearch"
## Model
USE_DUMMY_MODEL: true
CLIP_MODELS: {
  video: "LanguageBind_Video",
  audio: "LanguageBind_Audio",
  image: "LanguageBind_Image"
}
DEVICE: "cpu"
EMBEDDINGS_DIM: 768
## Constants
INDEX_PATH: "../data"
TMP_DIR: ".tmp"
