# Datasets Configuration
DATASETS:

# Frontend Settings
RESULT_COLUMNS: 4
CANDIDATES_PER_PAGE: 32
REQUESTS_TIMEOUT: 60000  # 60 seconds

# Backend Settings
BACKEND_URL: "http://localhost:8500"
EMBEDDER_TYPE: "LanguageBind"
DEVICE: "cpu"
STORAGE_TYPE: "Milvus"
MILVUS_URL: "http://localhost:19530"
MILVUS_DB_NAME: "ClipSeek"
INDEXES_ROOT: "../indexes"
TMP_DIR: ".tmp"

# General Settings
DEVELOPER_MODE: false
