services:
  frontend:
    image: e1four15f/clipseek-frontend:${VERSION}
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        BACKEND_URL: http://backend:8500
    ports:
      - "4173:${FRONTEND_PORT}"
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      - "backend"

  backend:
    image: e1four15f/clipseek-backend:${VERSION}
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8500:${BACKEND_PORT}"
    volumes:
      - ${HF_HOME:-~/.cache/huggingface}:/hf
      - ./config.yaml:/config.yaml
      - ./indexes:/indexes
      - ./data:/data
    environment:
      MILVUS_URL: http://milvus:19530
      HF_HOME: /hf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    depends_on:
      - "milvus"

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:${MILVUS_PORT}"
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - "etcd"
      - "minio"
      - "attu"

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  attu:
    container_name: attu
    image: zilliz/attu:dev
    environment:
      ATTU_LOG_LEVEL: info
      SERVER_PORT: 9080
      MILVUS_URL: "milvus:19530"
    ports:
      - "9080:${ATTU_PORT}"

volumes:
  etcd_data:
  minio_data:
  milvus_data:

networks:
  default:
    name: ClipSeek
